### ISSUE TITLE
WordPress with picture tag and scroll ?

### ISSUE THREAD

**Issue by robots4life** [tvler/lazy-progressive-enhancement#17]
I would love to use this with WordPress and the `picture` tag.
Have your script in the head, then have a bunch of `picture` tags with rendered source like this, so after your script has run over it
```
<picture id="pic-id-406">
  <source media="(min-width: 1025px)" srcset="http://example.com/image-1280x1280.jpg">
  <source media="(min-width: 641px)" srcset="http://example.com/image-768x768.jpg">
  <source media="(min-width: 426px)" srcset="http://example.com/image-640x640.jpg">
  <source media="(min-width: 181px)" srcset="http://example.com/image-320x320.jpg">
  <img src="http://example.com/image-320x320.jp.jpg" alt="a11y rocks">
</picture>
```

and with normal source (ctrl+u) like I read it in docs like this
```
<picture id="pic-id-406">
  <source media="(min-width: 1025px)" srcset="http://example.com/image-1280x1280.jpg">
  <source media="(min-width: 641px)" srcset="http://example.com/image-768x768.jpg">
  <source media="(min-width: 426px)" srcset="http://example.com/image-640x640.jpg">
  <source media="(min-width: 181px)" srcset="http://example.com/image-320x320.jpg">
    <noscript>
      <img src="http://example.com/image-320x213.jpg" alt="a11y rocks">
    </noscript>
</picture>
```

and at the bottom of page I have
```
<script>
	loadMedia(null, null, true);
</script>
```
However when I throttle and check network tab all the pictures load at once and the initiator is lazy-progressive-enhancement.js.

What am I doing wrong?
I mean the script works since the `noscript` part is there and is being changed, however the scroll part does not work.
At this stage I am not at all concerned with performance, I just like to get the script working, that would be fabulous. Thank you for any help.

**Comment by tvler** [comment]
Hi! Unfortunately this library doesn't work with picture elements yet :(

From your example it looks like you can actually use the `srcset` and `sizes` attributes on an img tag instead of a `picture` element for your use case though.

**Comment by robots4life** [comment]
I recently read all of this.
https://cloudfour.com/thinks/responsive-images-101-definitions/ all 10 parts
https://dev.opera.com/articles/responsive-images/
https://beta.observablehq.com/@eeeps/w-descriptors-and-sizes-under-the-hood
https://ericportis.com/posts/2014/srcset-sizes/
https://jakearchibald.com/2015/anatomy-of-responsive-images/
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

Now I understand that my use of picture source and media is not what I want, art-direction.
Resolution-switching is what I want and for that I can use the img tag, though since I now know more about all this I will include the picture tag with source srcet and type attribute to provide images of a different type to browsers that support it.

Since the art-direction use case directs to the browser explicitly to download this image on this particular media condition I can understand why lazy-loading cannot work well for this use case or why you have not yet been able to support it. Thank you.
